# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pokemonou_pb2 as pokemonou__pb2


class FeedbackStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckBoard = channel.unary_unary(
                '/Feedback/CheckBoard',
                request_serializer=pokemonou__pb2.Position.SerializeToString,
                response_deserializer=pokemonou__pb2.Position.FromString,
                )
        self.Move = channel.unary_unary(
                '/Feedback/Move',
                request_serializer=pokemonou__pb2.Position.SerializeToString,
                response_deserializer=pokemonou__pb2.Position.FromString,
                )
        self.Capture = channel.unary_unary(
                '/Feedback/Capture',
                request_serializer=pokemonou__pb2.Position.SerializeToString,
                response_deserializer=pokemonou__pb2.Catch.FromString,
                )
        self.Add = channel.unary_unary(
                '/Feedback/Add',
                request_serializer=pokemonou__pb2.Position.SerializeToString,
                response_deserializer=pokemonou__pb2.Position.FromString,
                )
        self.Del = channel.unary_unary(
                '/Feedback/Del',
                request_serializer=pokemonou__pb2.Position.SerializeToString,
                response_deserializer=pokemonou__pb2.Position.FromString,
                )
        self.Setup = channel.unary_unary(
                '/Feedback/Setup',
                request_serializer=pokemonou__pb2.Dim.SerializeToString,
                response_deserializer=pokemonou__pb2.Dim.FromString,
                )


class FeedbackServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Capture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Del(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Setup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeedbackServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckBoard,
                    request_deserializer=pokemonou__pb2.Position.FromString,
                    response_serializer=pokemonou__pb2.Position.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=pokemonou__pb2.Position.FromString,
                    response_serializer=pokemonou__pb2.Position.SerializeToString,
            ),
            'Capture': grpc.unary_unary_rpc_method_handler(
                    servicer.Capture,
                    request_deserializer=pokemonou__pb2.Position.FromString,
                    response_serializer=pokemonou__pb2.Catch.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=pokemonou__pb2.Position.FromString,
                    response_serializer=pokemonou__pb2.Position.SerializeToString,
            ),
            'Del': grpc.unary_unary_rpc_method_handler(
                    servicer.Del,
                    request_deserializer=pokemonou__pb2.Position.FromString,
                    response_serializer=pokemonou__pb2.Position.SerializeToString,
            ),
            'Setup': grpc.unary_unary_rpc_method_handler(
                    servicer.Setup,
                    request_deserializer=pokemonou__pb2.Dim.FromString,
                    response_serializer=pokemonou__pb2.Dim.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Feedback', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Feedback(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Feedback/CheckBoard',
            pokemonou__pb2.Position.SerializeToString,
            pokemonou__pb2.Position.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Feedback/Move',
            pokemonou__pb2.Position.SerializeToString,
            pokemonou__pb2.Position.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Capture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Feedback/Capture',
            pokemonou__pb2.Position.SerializeToString,
            pokemonou__pb2.Catch.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Feedback/Add',
            pokemonou__pb2.Position.SerializeToString,
            pokemonou__pb2.Position.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Del(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Feedback/Del',
            pokemonou__pb2.Position.SerializeToString,
            pokemonou__pb2.Position.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Setup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Feedback/Setup',
            pokemonou__pb2.Dim.SerializeToString,
            pokemonou__pb2.Dim.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
