# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pokemonou.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpokemonou.proto\"\x12\n\x03\x44im\x12\x0b\n\x03\x64im\x18\x01 \x01(\x05\"\x18\n\x08Greeting\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x1f\n\x07Outcome\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\".\n\x05\x43\x61tch\x12\x0f\n\x07outcome\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x05\x12\t\n\x01y\x18\x03 \x01(\x05\x32\xc5\x01\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12$\n\nCheckBoard\x12\t.Position\x1a\t.Position\"\x00\x12\x1e\n\x04Move\x12\t.Position\x1a\t.Position\"\x00\x12\x1e\n\x07\x43\x61pture\x12\t.Position\x1a\x06.Catch\"\x00\x12\x1d\n\x03\x41\x64\x64\x12\t.Position\x1a\t.Position\"\x00\x12\x1d\n\x03\x44\x65l\x12\t.Position\x1a\t.Position\"\x00\x12\x15\n\x05Setup\x12\x04.Dim\x1a\x04.Dim\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pokemonou_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIM._serialized_start=19
  _DIM._serialized_end=37
  _GREETING._serialized_start=39
  _GREETING._serialized_end=63
  _POSITION._serialized_start=65
  _POSITION._serialized_end=97
  _OUTCOME._serialized_start=99
  _OUTCOME._serialized_end=130
  _CATCH._serialized_start=132
  _CATCH._serialized_end=178
  _FEEDBACK._serialized_start=181
  _FEEDBACK._serialized_end=378
# @@protoc_insertion_point(module_scope)
